# Generated by Django 6.1 on 2026-08-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salamYusuf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='url',
            field=models.CharField(db_index=True, unique=True),
        ),
    ]
