# Generated by Django 6.1 on 2026-08-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salamYusuf', '0002_alter_tenant_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='url',
            new_name='domain',
        ),
    ]
