# Generated by Django 6.1 on 2026-08-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salamYusuf', '0003_rename_url_tenant_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
