import { useState, useRef } from 'react';
import "./tresultinputs.css"; 
import { LuPrinter, LuFileSpreadsheet, LuInfo, LuChevronLeft, LuSave, LuCircleAlert } from 'react-icons/lu';

export default function Tresultinputs() {
  const [term] = useState(2); 
  const fileInputRef = useRef(null);
  
  const [students] = useState([
    { id: 1, name: "Amadou Diallo", a1: 5, a2: 5, c1: 5, c2: 5, t1: 7, t2: 7, exam: 60, prevTerm: 70 },
    { id: 2, name: "Binta Bah", a1: 4, a2: 4, c1: 5, c2: 5, t1: 6, t2: 7, exam: 55, prevTerm: 80 },
  ]);

  const calcCA = (s) => (s.a1 + s.a2 + s.c1 + s.c2 + s.t1 + s.t2);

  return (
    <div className="formal-page-wrapper">
      {/* Header & Introduction */}
      <div className="no-print intro-section">
        <div className="sr-title-group">
          <button className="back-btn" onClick={() => window.history.back()}><LuChevronLeft /> Dashboard</button>
          <h1>Result Entry Portal</h1>
        </div>
        
        <div className="teacher-message-card">
          <p className="heartfelt-msg">
            "Dear teachers, we entrust you with the future of our students. In recording these results, 
            let honesty and truth be your guide. Your accuracy today shapes their opportunities tomorrow."
          </p>
          
          <div className="instruction-box">
            <h4><LuInfo /> Grading Instructions:</h4>
            <div className="instruction-grid">
              <ul>
                <li><strong>A1:</strong> Assignment (5mks)</li>
                <li><strong>A2:</strong> Attendance (5mks)</li>
                <li><strong>C1:</strong> Classwork (5mks)</li>
              </ul>
              <ul>
                <li><strong>C2:</strong> Other Activities (5mks)</li>
                <li><strong>T1:</strong> First Test (7.5mks)</li>
                <li><strong>T2:</strong> Second Test (7.5mks)</li>
              </ul>
            </div>
            <p className="calc-note">
              <LuCircleAlert /> <strong>System Logic:</strong> The <strong>Total CA</strong> is autogenerated by summing A1 through T2. 
              The <strong>Cum Avg</strong> is calculated as: $(Term 1 + Term 2) \div 2$.
            </p>
          </div>
        </div>
      </div>

      {/* Action Bar */}
      <div className="no-print formal-actions-bar">
        <div className="action-btns">
          <input type="file" ref={fileInputRef} style={{display: 'none'}} />
          <button className="btn-excel" onClick={() => fileInputRef.current.click()}><LuFileSpreadsheet /> Import Excel</button>
          <button className="btn-print" onClick={() => window.print()}><LuPrinter /> Print BroadSheet</button>
          <button className="btn-save"><LuSave /> Finalize & Submit</button>
        </div>
      </div>

      {/* THE FORMAL SHEET */}
      <div className="formal-sheet-container">
        <div className="sheet-header">
          <h2>NSCHS OFFICIAL ACADEMIC BROADSHEET</h2>
          <p><strong>SUBJECT:</strong> PHYSICS | <strong>CLASS:</strong> G11 SCIENCE | <strong>TERM:</strong> {term} | <strong>YEAR:</strong> 2026</p>
        </div>

        <table className="broadsheet-table">
          <thead>
            <tr>
              <th rowSpan="2" className="name-col">STUDENT NAME</th>
              <th colSpan="4">SCHOOL ACTIVITIES (20)</th>
              <th colSpan="2">TESTS (15)</th>
              <th rowSpan="2">TOTAL CA</th>
              <th rowSpan="2">EXAM (65)</th>
              <th rowSpan="2">TOTAL</th>
              <th rowSpan="2">PREV</th>
              <th rowSpan="2">CUM AVG</th>
            </tr>
            <tr className="sub-labels">
              <th>A1</th>
              <th>A2</th>
              <th>C1</th>
              <th>C2</th>
              <th>T1</th>
              <th>T2</th>
            </tr>
          </thead>
          <tbody>
            {students.map(s => {
              const ca = calcCA(s);
              const total = ca + s.exam;
              return (
                <tr key={s.id}>
                  <td className="student-name">{s.name}</td>
                  <td><input type="number" defaultValue={s.a1} /></td>
                  <td><input type="number" defaultValue={s.a2} /></td>
                  <td><input type="number" defaultValue={s.c1} /></td>
                  <td><input type="number" defaultValue={s.c2} /></td>
                  <td><input type="number" defaultValue={s.t1} /></td>
                  <td><input type="number" defaultValue={s.t2} /></td>
                  <td className="read-only-cell">{ca}</td>
                  <td><input type="number" className="exam-input" defaultValue={s.exam} /></td>
                  <td className="read-only-cell bold">{total}</td>
                  <td>{term === 1 ? '-' : s.prevTerm}</td>
                  <td className="read-only-cell bold">{(term === 1 ? total : (total + s.prevTerm)/2).toFixed(1)}</td>
                </tr>
              );
            })}
          </tbody>
        </table>

        <div className="sheet-footer">
          <div className="sig-line">Subject Teacher Signature</div>
          <div className="sig-line">Principal / VP Academic</div>
        </div>
      </div>
    </div>
  );
}